### ISSUE TITLE
Flash-beskeder skubber dashboard-menuen ned

### ISSUE THREAD

**Issue by slimcdk** [Jakobtottrup/OptekSemester2#58]

**Comment by SebastianAndresen** [comment]
Hvordan kan jeg teste det? Jeg kunne forestille mig, at det er fordi flash-beskederne har sin egen container, men jeg ved ikke hvordan jeg får den til at vise en besked

**Comment by slimcdk** [comment]
Den har sin egen container - HTML elementerne er i layouts.handlebars:74
Du kan trigger en flash besked, ved at deltage og forlade siddegrupper - siden skal dog manuelt opdateres, for at beskeden vises

**Comment by Jakobtottrup** [comment]
Fixed
