### ISSUE TITLE
Pladsgrupper

### ISSUE THREAD

**Issue by SebastianAndresen** [Jakobtottrup/OptekSemester2#59]
Man skal ikke skrive adgangskoden for at deltage i en pladsgruppe. Ved opretning af gruppe, kan man ikke vælge om adgangskode er nødvendigt for andre / om gruppen er åben for alle eller er en lukket gruppe. Når man er i en gruppe, står der "forlad gruppe" ud for alle grupperne.

**Comment by slimcdk** [comment]
Adgangskode er ved at blive tilføjet. Om der skal være adgangskode eller ej, er vist en 'nice to have' feature lige pt.
Forlad gruppe osv. er fixet

**Comment by slimcdk** [comment]
Done
